// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIzirW2XlWStdJ0aLkqWzmMYQ4jFE3mQU',
    appId: '1:1086150900550:web:0da020c72551609af40347',
    messagingSenderId: '1086150900550',
    projectId: 'task-manager-83d2d',
    authDomain: 'task-manager-83d2d.firebaseapp.com',
    storageBucket: 'task-manager-83d2d.firebasestorage.app',
    measurementId: 'G-HXP8ZZHMR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIgZaBRskyub6eiklK0qtblbtJhVXjVa4',
    appId: '1:1086150900550:android:73807131f2edc2ecf40347',
    messagingSenderId: '1086150900550',
    projectId: 'task-manager-83d2d',
    storageBucket: 'task-manager-83d2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqYXDZ5Y_ir6kArMlBvozTAJCPx3QomKk',
    appId: '1:1086150900550:ios:c907f530970fd0c3f40347',
    messagingSenderId: '1086150900550',
    projectId: 'task-manager-83d2d',
    storageBucket: 'task-manager-83d2d.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqYXDZ5Y_ir6kArMlBvozTAJCPx3QomKk',
    appId: '1:1086150900550:ios:c907f530970fd0c3f40347',
    messagingSenderId: '1086150900550',
    projectId: 'task-manager-83d2d',
    storageBucket: 'task-manager-83d2d.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIzirW2XlWStdJ0aLkqWzmMYQ4jFE3mQU',
    appId: '1:1086150900550:web:15c9e2af7bb2a9e5f40347',
    messagingSenderId: '1086150900550',
    projectId: 'task-manager-83d2d',
    authDomain: 'task-manager-83d2d.firebaseapp.com',
    storageBucket: 'task-manager-83d2d.firebasestorage.app',
    measurementId: 'G-C1WWPWQHSP',
  );
}
